CREATE TABLE `stock_model` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL COMMENT '日期',
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '股票名称',
  `code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '股票代码',
  `market_capitalization` bigint(20) NOT NULL COMMENT '总股本',
  `circulating_market_capitalization` bigint(20) NOT NULL COMMENT '流通股本',
  `real_circulating_capitalization` bigint(20) NOT NULL COMMENT '真实流通股本',
  `price` decimal(10,2) NOT NULL COMMENT '最新价',
  `volume` bigint(20) NOT NULL COMMENT '成交量(手)',
  `turnover_rate` decimal(5,2) NOT NULL COMMENT '换手率(%)',
  `real_turnover_rate` decimal(5,2) NOT NULL COMMENT '真实换手率(%)',
  `outside_volume` bigint(20) NOT NULL COMMENT '外盘',
  `inside_volume` bigint(20) NOT NULL COMMENT '内盘',
  `buy_1_vol` bigint(20) DEFAULT NULL COMMENT '买一量',
  `first_volume` bigint(20) NOT NULL COMMENT '首笔成交量(手)',
  `first_price` decimal(10,2) NOT NULL COMMENT '首笔成交价格',
  `last_volume` bigint(20) NOT NULL COMMENT '最后一笔成交量(手)',
  `last_price` decimal(10,2) NOT NULL COMMENT '最后一笔成交价格',
  `first_seal_time` time DEFAULT NULL COMMENT '首次封板时间',
  `last_seal_time` time DEFAULT NULL COMMENT '最后封板时间',
  `first_break_time` time DEFAULT NULL COMMENT '首次炸板时间',
  `last_break_time` time DEFAULT NULL COMMENT '最后炸板时间',
  `break_count` int(11) NOT NULL DEFAULT '0' COMMENT '炸板次数',
  `dc_first_seal_time` time DEFAULT NULL COMMENT '东财首次封板时间',
  `dc_last_seal_time` time DEFAULT NULL COMMENT '东财最后封板时间',
  `dc_break_count` int(11) NOT NULL DEFAULT '0' COMMENT '东财炸板次数',
  `limit_up_statistics` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '涨停统计',
  `limit_up_days` int(11) DEFAULT NULL COMMENT '连板数,为空说明当天未涨停',
  `amplitude` decimal(5,2) DEFAULT NULL COMMENT '振幅(%)',
  `industry` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '所属行业',
  `events` json DEFAULT NULL COMMENT '炸板事件(JSON)',
  PRIMARY KEY (`id`),
  KEY `idx_code_date` (`code`,`date`),
  KEY `idx_date` (`date`)
) ENGINE=InnoDB AUTO_INCREMENT=2346 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票涨停板数据模型'